### ISSUE TITLE
Redundant cycles from Molecule._find_cycles()

### ISSUE THREAD

**Issue by dav3794** [dav3794/PsiMol#4]
The Molecule._find_cycles() returns redundant cycles for:
1. Singular rings - for one ring with n nodes, returns 2n different cycles, each starting from different node (n) and going once clockwise and once anti-clockwise (+n). Thus, for one 6-node ring, it finds 12 cycles instead of 1.
2. Multiple rings - in the case of two or more adjacent rings (sharing at least one edge), the function returns also supercycles - cycles that can be created from singular rings. For instance, for pyrene (example xyz file [here](https://github.com/nutjunkie/IQmol/blob/master/share/fragments/Molecules/Polyaromatic_Hydrocarbons/Pyrene.xyz)), the function should return only 4 cycles (for 4 singular rings). Instead, running `len(mol._find_cycles(mol.bonds))`, where mol if Molecule created from the above xyz file, returns 280 cycles.

**Comment by ArnoldLowefel** [comment]
fixed
